const adjectives = [
    'radiant', 'blissful', 'vibrant', 'serene', 'jubilant', 'luminous', 'energetic', 'harmonious', 'majestic', 'tranquil',
    'zealous', 'whimsical', 'enigmatic', 'resilient', 'ethereal', 'shadow', 'phantom', 'neon', 'crimson', 'frost',
    'blaze', 'thunder', 'vortex', 'iron', 'steel', 'obsidian', 'titan', 'raven', 'onyx', 'eclipse',
    'nova', 'inferno', 'storm', 'venom', 'chaos', 'solar', 'lunar', 'forest', 'oceanic', 'mountain',
    'desert', 'river', 'sky', 'meadow', 'aurora', 'coral', 'pine', 'birch', 'maple', 'willow',
    'cedar', 'stone', 'cloud', 'tide', 'bubbly', 'snazzy', 'zippy', 'wacky', 'jolly', 'quirky',
    'fuzzy', 'giggly', 'peppy', 'dizzy', 'bouncy', 'cheery', 'sassy', 'puffy', 'wobbly', 'silly',
    'goofy', 'zesty', 'fluffy', 'chirpy', 'arcane', 'celestial', 'mystic', 'enchanted', 'mythic', 'divine',
    'spectral', 'cosmic', 'ancient', 'legendary', 'warlock', 'sorcerer', 'dragon', 'phoenix', 'cyber', 'quantum',
    'pixel', 'atomic', 'robotic', 'virtual', 'digital', 'hyper', 'nano', 'sonic', 'laser', 'plasma',
    'hologram', 'circuit', 'matrix', 'drone', 'galaxy', 'orbital', 'infinite', 'mighty', 'fearless', 'valiant',
    'fierce', 'bold', 'brave', 'dynamic', 'intense', 'relentless', 'unstoppable', 'dominant', 'supreme', 'invincible',
    'heroic', 'ironclad', 'thunderous', 'savage', 'vicious', 'snuggle', 'cuddly', 'sweetie', 'honey', 'sugar',
    'berry', 'bubble', 'puddle', 'sprinkle', 'cupcake', 'marshmallow', 'pudding', 'jellybean', 'gummy', 'peaches',
    'muffin', 'cookie', 'sparkle', 'twinkle', 'doodle', 'midnight', 'abyss', 'void', 'wraith', 'specter',
    'dusk', 'twilight', 'ghost', 'cursed', 'haunted', 'sinister', 'darkling', 'nightshade', 'umbra', 'quixotic',
    'nebulous', 'ephemeral', 'zephyr', 'solstice', 'equinox', 'arcadian', 'halcyon', 'sylvan', 'nocturnal', 'cimmerian',
    'sable', 'opalescent', 'iridescent', 'gossamer', 'cerulean', 'vermilion', 'radiant', 'blissful', 'vibrant', 'serene',
    'jubilant', 'luminous', 'energetic', 'harmonious', 'majestic', 'tranquil', 'zealous', 'whimsical', 'enigmatic', 'resilient',
    'ethereal', 'shadow', 'phantom', 'neon', 'crimson', 'frost', 'blaze', 'thunder', 'vortex', 'iron',
    'steel', 'obsidian', 'titan', 'raven', 'onyx', 'eclipse', 'nova', 'inferno', 'storm', 'venom',
    'chaos', 'solar', 'lunar', 'forest', 'oceanic', 'mountain', 'desert', 'river', 'sky', 'meadow',
    'aurora', 'coral', 'pine', 'birch', 'maple', 'willow', 'cedar', 'stone', 'cloud', 'tide',
    'bubbly', 'snazzy', 'zippy', 'wacky', 'jolly', 'quirky', 'fuzzy', 'giggly', 'peppy', 'dizzy',
    'bouncy', 'cheery', 'sassy', 'puffy', 'wobbly', 'silly', 'goofy', 'zesty', 'fluffy', 'chirpy',
    'arcane', 'celestial', 'mystic', 'enchanted', 'mythic', 'divine', 'spectral', 'cosmic', 'ancient', 'legendary',
    'warlock', 'sorcerer', 'dragon', 'phoenix', 'cyber', 'quantum', 'pixel', 'atomic', 'robotic', 'virtual',
    'digital', 'hyper', 'nano', 'sonic', 'laser', 'plasma', 'hologram', 'circuit', 'matrix', 'drone',
    'galaxy', 'orbital', 'infinite', 'mighty', 'fearless', 'valiant', 'fierce', 'bold', 'brave', 'dynamic',
    'intense', 'relentless', 'unstoppable', 'dominant', 'supreme', 'invincible', 'heroic', 'ironclad', 'thunderous', 'savage',
    'vicious', 'snuggle', 'cuddly', 'sweetie', 'honey', 'sugar', 'berry', 'bubble', 'puddle', 'sprinkle',
    'cupcake', 'marshmallow', 'pudding', 'jellybean', 'gummy', 'peaches', 'muffin', 'cookie', 'sparkle', 'twinkle',
    'doodle', 'midnight', 'abyss', 'void', 'wraith', 'specter', 'dusk', 'twilight', 'ghost', 'cursed',
    'haunted', 'sinister', 'darkling', 'nightshade', 'umbra', 'quixotic', 'nebulous', 'ephemeral', 'zephyr', 'solstice',
    'equinox', 'arcadian', 'halcyon', 'sylvan', 'nocturnal', 'cimmerian', 'sable', 'opalescent', 'iridescent', 'gossamer',
    'cerulean', 'vermilion'
];

export default adjectives;